##
#      ____   _   _   _ _        _    
#     |  _ \ / \ | | | | |      / \   
#     | |_) / _ \| | | | |     / _ \  
#     |  __/ ___ \ |_| | |___ / ___ \ 
#     |_| /_/   \_\___/|_____/_/   \_\
#
#
# Personal
# Artificial
# Unintelligent
# Life
# Assistant
#
##

PAULA's input package

VERSION 0.2.2

* Provided
** string.py
   - prompt_for_input_string(prompt=conf.INPUT_PROMPT)
     Get's a string from the user.
   - prompt_with_timeout(timeout, prompt=conf.INPUT_PROMPT)
     Waits <timeout> seconds for input from the user.
     Returns an empty string if the input times out.
** integer.py
   - prompt_for_input_int(prompt=conf.INPUT_PROMPT)
     Get's an integer from the user.
     Returns None if the input was not an integer.
   - prompt_with_timeout(timeout, prompt=conf.INPUT_PROMPT)
     Waits <timeout> seconds for input from the user.
     Returns None if the input times out or the input was not an integer.
** list.py
   - promt_for_list(possible_selections, sortAlphabetically=True)
     Lets the user choose from a list of items which are automatically indexed.
     Returns the chosen item.
   - prompt_for_dict(possible_selections, sortAlphabetically=True)
     Lets the user choose from a dictionary of items. The keys will be used as indexes.
     Returns the chosen entry.
* Required
Nothing
