##
#      ____   _   _   _ _        _    
#     |  _ \ / \ | | | | |      / \   
#     | |_) / _ \| | | | |     / _ \  
#     |  __/ ___ \ |_| | |___ / ___ \ 
#     |_| /_/   \_\___/|_____/_/   \_\
#
#
# Personal
# Artificial
# Unintelligent
# Life
# Assistant
#
##

The core module is the core of PAULA, it provides all PAULA's core functionality.

VERSION 0.1

* Provided
** inputs.py
   - get_string()
   Asks the user for a string input.
   - get_integer()
   Asks the user for an integer input.
   - get_string_timeout(timeout)
   - get_integer_timeout(timeout)
   - get_item_from_list(possible_selections, sortAlphabetically=True)
     Returns the value chosen by the user
   - get_item_from_dict(possible_selections, sortAlphabetically=True)
     Returns the key chosen by the user
** interaction.py
   - decide_meaning(string)
   Decides what the given string means, returns the meaning.
   - means(string, meaning)
   Decides whether the given string corresponds to the given meaning.
   - say(text)
   Has PAULA say <text>.
** outputs.py
   - print_error(error_string)
   Prints the given error.
   - print_debug(debug_string)
   Prints the given debug info.
   - print_color(text, foreground, background="default", bold=False, newline=True)
   prints the given text in color.
** system.py
   - call(command_string, sync=True)
   calls the given command
   - call_list(command_list, sync=True)
   calls the given command in list format
   - call_silently(command_string, sync=True)
   calss the given command silently
   - call_list_silently(command_list, sync=True)
   calls the given command in list format silently
   - get_output_of(command_string)
   Returns the output of running the given command.
** util.py
   - get_operand(command, seperator_character=',')
   Returns the operand in the given command.
* Required
** command
** paula_input
** paula_output
** paula_system
** speak
** system

