##
#      ____   _   _   _ _        _    
#     |  _ \ / \ | | | | |      / \   
#     | |_) / _ \| | | | |     / _ \  
#     |  __/ ___ \ |_| | |___ / ___ \ 
#     |_| /_/   \_\___/|_____/_/   \_\
#
#
# Personal
# Artificial
# Unintelligent
# Life
# Assistant
#
##

The music module contains all PAULA's functionality conserning music.

* Provided
** song.py
  - Class: Song
    - properties
      - title
        Title of the song
      - artist
        Artist of the song
      - album
        Album of the song
      - path
        Path to the song
    - play()
      plays itself

  - choose_and_play()
    Has the user choose a song or choose to have a random song selected and plays it.

  - get_current_song()
    Returns the playing song. Returns None if no song is playing.

  - get_current_album()
    Returns the playing album. Returns None if no song is playing.

  - get_current_artist()
    Returns the playing artist. Returns None if no song is playing.
  
  - play_random()
    Plays a random song
    
  - choose()
    Has the user choose a song or choose to have a random song selected.

  - select()
    Has the user select a song and returns it
    
** system_volume.py
  - get()
  - set(percent)
  - mute()

* Required
** volume
*** volume.py
    - get()
    - set(percent)
    - mute()
